spring:
  application:
    name: cloud-user-server
#  profiles:
#    active: dev
  cloud:
    nacos:
      discovery:
        namespace: public
      #        server-addr: 192.168.0.229:8848
      config:
#        server-addr: 192.168.0.229:8848
        file-extension: yml
        namespace: public
      server-addr: 192.168.0.229:8848
      username: nacos
      password: nacos
#        prefix: ${spring.application.name}