spring:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
        uri-encoding: UTF-8
  rest:
    connection-timeout: 5000
    read-timeout: 5000
  cache-manager:
    entry-ttl: 8
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 192.168.21.103:9092
          auto-create-topics: true
          auto-add-partitions: true
        bindings:
          baseTenantInput:
            destination: topic-base-tenant
            consumer:
              autoCommitOffset: false
          baseDepartmentInput:
            destination: topic-base-department
            consumer:
              autoCommitOffset: false
          baseUserInput:
            destination: topic-base-user
            consumer:
              autoCommitOffset: false
      bindings:
        baseTenantInput:
          binder: kafka
          group: USER-CENTER-GROUP
          destination: topic-base-tenant
          consumer:
            concurrency: 1
        baseDepartmentInput:
          binder: kafka
          group: USER-CENTER-GROUP
          destination: topic-base-department
          consumer:
            concurrency: 1
        baseUserInput:
          binder: kafka
          group: USER-CENTER-GROUP
          destination: topic-base-user
          consumer:
            concurrency: 1
        baseTenantOutput:
          binder: kafka
          destination: topic-base-tenant
        baseDepartmentOutput:
          binder: kafka
          destination: topic-base-department
        baseUserOutput:
          binder: kafka
          destination: topic-base-user
  ## redis配置项
  redis:
    password: wshoto@2020
    host: 192.168.21.104
    port: 6379